BATest/Models/ErrorViewModel.cs
using System;

namespace BATest.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BATest/Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using BATest.Models;
using BATest.Utilities;
using Infrastructure;
using Infrastructure.DtoModel;
using Infrastructure.Entity;
using Repository.Interfaces;

namespace BATest.Controllers
{
    public class PersonController : Controller
    {
        private readonly ILogger<PersonController> _logger;
        public PersonController(ILogger<PersonController> logger)
        {
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            var result = await Client.Instance.GetAsync<List<PersonDto>>("person/getall");
            return View(result);
        }

        public IActionResult NewPerson()
        {
            return View();
        }

        public async Task<IActionResult> CreatePerson(PersonDto person)
        {
            var result = await Client.Instance.PostAsync<bool>("person/createperson",person);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeletePerson(string id)
        {
            var result = await Client.Instance.DeleteAsync<bool>("person/deleteperson",new {id=id});
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Contact(string id)
        {
            ViewBag.PersonId = id;
            var result = await Client.Instance.GetAsync<List<ContactDto>>("person/getallcontacts",new {id=id});
            return View(result);
        }
        
        public IActionResult NewContact(string id)
        {
            ViewBag.PersonId = id;
            return View();
        }
        
        public async Task<IActionResult> RemoveContact(string id,string contactId)
        {
            //var result = await _personRepository.RemoveContact(new Guid(id),new Guid(contactId));
            var result = await Client.Instance.DeleteAsync<bool>("person/removecontact",new {id=id,contactId=contactId});
            return RedirectToAction("Contact",new {id = id});
        }
        
        public async Task<IActionResult> AddContact(ContactDto contact)
        {
            //var result = await _personRepository.AddContact(contact);
            var result = await Client.Instance.PostAsync<bool>("person/addcontact",contact);
            return RedirectToAction("Contact",new {id = contact.PersonId});
        }
        
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

BATest/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using BATest.Models;
using BATest.Utilities;
using Infrastructure;
using Infrastructure.DtoModel;
using Infrastructure.Entity;
using Repository.Interfaces;

namespace BATest.Controllers
{
    public class ReportController : Controller
    {
        private readonly ILogger<ReportController> _logger;
        public ReportController(ILogger<ReportController> logger)
        {
            _logger = logger;
        }

        public async Task<IActionResult> CreateReport()
        {
            var result = await Client.Instance.PostAsync<bool>("report/createreport",null);
            return View("Success");
        }

        public async Task<IActionResult> ReportList()
        {
            var result = await Client.Instance.GetAsync<List<ReportDto>>("report/getreportlist");
            return View(result);
        }

        public async Task<IActionResult> Detail(string id)
        {
            var result = await Client.Instance.GetAsync<List<ReportDetailDto>>("report/getreportdetaillist",new {reportId = id});
            return View(result);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

BATest/Views/Person/Contact.cshtml
@{
    ViewData["Title"] = "Person Page";
}
@model List<Infrastructure.DtoModel.ContactDto>

<div class="text-left">
    <h3 class="display-5">İletişim Bilgileri</h3>
</div>

<div class="">
    <a class="btn btn-primary my-3" href="/Person/NewContact/@(ViewBag.PersonId)">Yeni İletişim Bilgisi</a>
    
    <table class="table table-hover">
        <thead>
        <tr>
            <td>Email</td>
            <td>Telno</td>
            <td>Konum</td>
            <td></td>
        </tr>
        </thead>
        <tbody>
        @if (Model != null)
        {
            foreach (var contact in Model)
            {
                <tr>
                    <td>@contact.Email</td>
                    <td>@contact.TelNo</td>
                    <td>@contact.Location</td>
                    <td class="text-right">
                        <a href="/Person/RemoveContact/@(ViewBag.PersonId + "/?contactId=" + contact.Id)" class="btn btn-danger">Sil</a>
                    </td>
                </tr>
            }
        }
        </tbody>
    </table>
</div>

BATest/Views/Person/Index.cshtml
@{
    ViewData["Title"] = "Person Page";
}
@model List<Infrastructure.DtoModel.PersonDto>

<div class="text-left">
    <h3 class="display-5">Person List</h3>
</div>

<div class="">
    <table class="table table-hover">
        <thead>
        <tr>
            <td>Ad</td>
            <td>Soyad</td>
            <td>Şirket</td>
            <td></td>
        </tr>
        </thead>
        <tbody>
        @if(Model != null)
        {
            foreach (var person in Model)
            {
                <tr>
                    <td>@person.Name</td>
                    <td>@person.Surname</td>
                    <td>@person.Company</td>
                    <td class="text-right">
                        <a href="/Person/Contact/@(person.PersonId)" class="btn btn-info">İletişim</a>
                        <a href="/Person/DeletePerson/@(person.PersonId)" class="btn btn-danger">Sil</a>
                    </td>
                </tr>
            }
        }
        </tbody>
    </table>
</div>

BATest/Views/Person/NewContact.cshtml
@{
    ViewData["Title"] = "Person Page";
}
@model Infrastructure.DtoModel.ContactDto

<div class="text-left">
    <h3 class="display-5">New Person</h3>
</div>

<div class="">
    <form asp-controller="Person" asp-action="AddContact" method="post">
        <div class="row">
            <div class="col-lg-6">
                <label>Email</label>
                <input type="text" class="form-control" asp-for="Email"/>
            </div>
            <div class="col-lg-6">
                <label>Tel No</label>
                <input type="text" class="form-control" asp-for="TelNo"/>
            </div>
            <div class="col-lg-12">
                <label>Konum</label>
                <input type="text" class="form-control" asp-for="Location"/>
            </div>
            <input asp-for="PersonId" value="@ViewBag.PersonId" style="display: none"/>
        </div>

        <div class="row">
            <div class="col-lg-12 text-right">
                <button type="submit" class="btn btn-primary mt-3">
                    Kaydet
                </button>
            </div>
        </div>
    </form>
</div>

BATest/Views/Person/NewPerson.cshtml
@{
    ViewData["Title"] = "Person Page";
}
@model Infrastructure.DtoModel.PersonDto

<div class="text-left">
    <h3 class="display-5">New Person</h3>
</div>

<div class="">
    <form asp-controller="Person" asp-action="CreatePerson" method="post">
        <div class="row">
            <div class="col-lg-6">
                <label>Ad</label>
                <input type="text" class="form-control" asp-for="Name"/>
            </div>
            <div class="col-lg-6">
                <label>Soyad</label>
                <input type="text" class="form-control" asp-for="Surname"/>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <label>Şirket</label>
                <input type="text" class="form-control" asp-for="Company"/>
            </div>
        </div>
        
        <div class="row">
            <div class="col-lg-12 text-right">
                <button type="submit" class="btn btn-primary mt-3">
                    Kaydet
                </button>
            </div>
        </div>
    </form>
</div>

BATest/Views/Report/Detail.cshtml
@{
    ViewData["Title"] = "Person Page";
}
@model List<Infrastructure.DtoModel.ReportDetailDto>
<div class="text-left">
    <h3 class="display-5">Rapor Listesi</h3>
</div>

<div class="">
    <table class="table table-hover">
        <thead>
        <tr>
            <td>Konum</td>
            <td>Kişi Sayısı</td>
            <td>Telefon No Sayısı</td>
        </tr>
        </thead>
        <tbody>
        @if(Model != null)
        {
            foreach (var reportDetail in Model)
            {
                <tr>
                    <td>@reportDetail.Location</td>
                    <td>@reportDetail.PersonCount</td>
                    <td>@reportDetail.TelNoCount</td>
                </tr>
            }
        }
        </tbody>
    </table>
</div>

BATest/Views/Report/ReportList.cshtml
@{
    ViewData["Title"] = "Person Page";
}
@model List<Infrastructure.DtoModel.ReportDto>
<div class="text-left">
    <h3 class="display-5">Rapor Listesi</h3>
</div>

<div class="">
    <table class="table table-hover">
        <thead>
        <tr>
            <td>Tarih</td>
            <td>Durum</td>
            <td></td>
        </tr>
        </thead>
        <tbody>
        @if(Model != null)
        {
            foreach (var report in Model)
            {
                <tr>
                    <td>@report.ReportDate</td>
                    <td>@report.ReportState</td>
                    <td class="text-right">
                        <a href="/report/detail/@(report.ReportId)" class="btn btn-info">Detay</a>
                    </td>
                </tr>
            }
        }
        </tbody>
    </table>
</div>

BATest/Views/Report/Success.cshtml
@{
    ViewData["Title"] = "Person Page";
}

<div class="text-center">
    <h3 class="display-5">Raporunuz hazırlanıyor. Aşağıdaki bağlantıdan takip edebilirsiniz</h3>
    <a href="/report/reportlist">Raporlarım</a>
</div>

BATest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - BATest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Person" asp-action="Index">BATest</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="Index">Kişi Listesi</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="NewPerson">Yeni Kişi</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Report" asp-action="ReportList">Rapor Listesi</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Report" asp-action="CreateReport">Yeni Rapor Talebi</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2020 - BATest 
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>